### ISSUE TITLE
Using `Theme.MaterialComponents` throws errors.

### ISSUE THREAD

**Issue by KevCron** [verygoodsecurity/vgs-collect-android#325]
**Describe the bug**
Unable to use `VGSTextInputLayout` in apps that use `Theme.Material`

**To Reproduce**
1. Create any app using an app theme that is not `Theme.AppCompat` or a descendant.
2. Create any layout using `VGSTextInputLayout`.
3. Experience the error in the screenshot upon trying to inflate the layout.

**Expected behavior**

`VGSTextInputLayout` does not throw errors.

**Screenshots**

<img width="1269" alt="Screen Shot 2021-12-24 at 11 16 05 PM" src="https://user-images.githubusercontent.com/9090280/147378012-ece55678-25dd-4255-818d-85de0fa775f6.png">

**Environment (please complete the following information):**
 - SDK Version: 30
 - Android Version: 12
 - Device: Samsung S21 5G

**Additional context**
I'm creating this app with Flutter, so I'm not sure if I can easily change the entire app theme to `AppCompat` instead of `MaterialComponents`.

**Possible Solution**
Migrating to an `AppCompat` theme, but I don't prefer to do this.

Is needing to use an `AppCompat` theme by design, or is this just an oversight? Is there some solution I'm not seeing?

**Comment by Endorf** [comment]
Thank you for informing us about this issue.
We will have a look at this.

**Comment by Endorf** [comment]
Hi, @KevCron.
Could you try to use `Theme.MaterialComponents` instead of `Theme.Material`? The `Theme.MaterialComponents` is descendant of the `AppCompat`, so it could work in your case.
VGS Collect SDK has minSdkVersion(19). The `Theme.Material` supports only from 21 api level. You can't use `Theme.Material` with VGS Collect SDK because we have to use `Theme.MaterialComponents` to support 19 api level.
